apiVersion: v1
kind: ConfigMap
metadata:
  name: sso-gateway-nginx-proxy-server-conf
  labels:
    {{- include "ssoGateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx-proxy
data:
  server-blocks.conf: |
      # Generate server blocks for each configured server domain

      {{- range $server := .Values.global.servers }}
      server {
          listen {{ $.Values.service.ports.https }};
          listen [::]:{{ $.Values.service.ports.https }};
          server_name {{ $server.domain }};
          error_page 401 403 = @login_required;

          # headers for reverse proxy and SSO
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Original-URI $request_uri;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;

          proxy_connect_timeout       75s;
          proxy_send_timeout          75s;
          proxy_read_timeout          300s;

          location / {
            auth_request /auth/;
            auth_request_set $auth_status $upstream_status;
            proxy_set_header Host {{ $server.domain }};
            proxy_pass http://{{ $server.hostname }}/;
          }

          location /auth/ {
            internal;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
            proxy_pass http://sso-gateway-client-svc/;
          }

          location /sso-login {
            proxy_set_header Host $host;
            proxy_pass http://sso-gateway-client-svc/authn;
          }

          location /sso {
            proxy_set_header Host $host;
            proxy_pass http://sso-gateway-client-svc/authn/callback;
          }

          location @login_required {
            return 302 {{ $server.domain }}/sso-login?relay=$request_uri;
          }
        }
        {{- end }}
      
