{{- if and .Values.enabled (not .Values.ingress.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssoGateway.fullname" . }}-svc
  labels:
    {{- include "ssoGateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx-proxy
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
    - name: https
      protocol: TCP
      port: 8081
      targetPort: https
  selector:
    app.kubernetes.io/instance: sso-gateway
    app.kubernetes.io/name: nginx
{{- end }}