apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssoGateway.fullname" . }}-client
  labels:
    {{- include "ssoGateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ssoClient.autoscaling.enabled }}
  replicas: {{ .Values.ssoClient.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ssoGateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # 1. Vault injector configuration
        vault.hashicorp.com/agent-inject: 'true'
        # set to 'true' if you are going to connect and query vault from your application
        vault.hashicorp.com/agent-inject-token: 'false' 
        # this makes sure the secret vault will only change during pod restart
        vault.hashicorp.com/agent-pre-populate-only: 'true' 
        # Must match cluster. Use one of: k8s-silver, k8s-gold, k8s-golddr, k8s-emerald
        vault.hashicorp.com/auth-path: auth/k8s-{{ .Values.global.cluster }}  
        vault.hashicorp.com/namespace: platform-services
        # licenseplate-nonprod or licenseplate-prod are your options
        vault.hashicorp.com/role: {{ .Values.global.vault.role }} 
        # Configure how to retrieve and populate the secrets from Vault:
        # - The name of the secret is any unique string after vault.hashicorp.com/agent-inject-secret-<name>
        # - The value is the path in Vault where the secret is located.
        vault.hashicorp.com/agent-inject-secret-secrets-conf: {{  .Values.global.vault.secret }}
        # - The template Vault Agent should use for rendering a secret:
        vault.hashicorp.com/agent-inject-secret-secrets: {{ .Values.global.vault.path }}
        vault.hashicorp.com/agent-inject-template-secrets: |
          {{`{{- with secret `}}"{{ .Values.global.vault.path }}"{{` }}
          {{- range $k, $v := .Data.data }}
          {{ $k }}={{ $v }}{{ end -}}
          {{- end `}} }}
      {{- with .Values.ssoClient.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ssoGateway.labels" . | nindent 8 }}
        {{- with .Values.ssoClient.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.ssoClient.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ssoGateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ssoClient.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          # args:
          #   ['sh', '-c', 'source {{ .Values.global.vault.path }}']
          securityContext:
            {{- toYaml .Values.ssoClient.securityContext | nindent 12 }}
          image: {{ .Values.ssoClient.image.repository }}:{{ .Values.ssoClient.image.tag }}
          imagePullPolicy: {{ .Values.ssoClient.image.pullPolicy }} 
          ports: 
            - name: http
              containerPort: {{ .Values.ssoClient.service.port }}
              protocol: TCP
          {{- if .Values.ssoClient.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.ssoClient.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.ssoClient.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.ssoClient.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.ssoClient.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.ssoClient.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.ssoClient.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.ssoClient.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.ssoClient.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.ssoClient.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.ssoClient.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.ssoClient.probes.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.ssoClient.resources | nindent 12 }}
          env:
            {{- if .Values.ssoClient.env }} 
            {{- toYaml .Values.ssoClient.env | trimSuffix "\n" | nindent 12 }}
            {{- end }}
            - name: SSO_CLIENT_PORT
              value: {{  .Values.ssoClient.service.port }}
            - name: NGINX_PROXY_URL
              value: http://{{ include "ssoGateway.fullname" . }}-proxy:{{ .Values.nginx.service.ports.http }}
            - name: REDIS_STORE_URL
              value: http://{{ include "ssoGateway.fullname" . }}-redis:{{ .Values.redis.service.port }}
            - name: REDIRECT_URL
              value: http://{{ include "ssoGateway.fullname" . }}-client:{{ .Values.ssoClient.service.port }}/authn/callback
            - name: VAULT_CONFIG_PATH
              value: {{  .Values.global.vault.containerPath }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sso-gateway-global-conf
                  key: redisPassword
            - name: SSO_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: sso-gateway-global-conf
                  key: ssoSessionSecret
          envFrom:
            {{- toYaml .Values.ssoClient.envFrom | nindent 12 }}
          {{- with .Values.ssoClient.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.ssoClient.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ssoClient.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ssoClient.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ssoClient.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}