# sso-gateway/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sso-gateway-global-conf
  labels:
    {{- include "ssoGateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: ssoClient
type: Opaque
data:
  SSO_AUTH_SERVER_URL: {{ .Values.ssoClient.secrets.SSO_AUTH_SERVER_URL | b64enc | quote }}
  SSO_REALM: {{ .Values.ssoClient.secrets.SSO_REALM | b64enc | quote }}
  SSO_CLIENT_ID: {{ .Values.ssoClient.secrets.SSO_CLIENT_ID | b64enc | quote }}
  SSO_REDIRECT_URL: {{ .Values.ssoClient.secrets.SSO_REDIRECT_URL | b64enc | quote }}
  SSO_LOGOUT_REDIRECT_URI: {{ .Values.ssoClient.secrets.SSO_LOGOUT_REDIRECT_URI | b64enc | quote }}
  CLIENT_HOST: {{ .Values.ssoClient.secrets.CLIENT_HOST | b64enc | quote }}

  # SSO_CLIENT_SECRET - conditionally generate or use provided value
  ssoClientSecret: |-
    {{- if and .Values.ssoClient.secrets.ssoClientSecret.generate (not .Values.ssoClient.secrets.ssoClientSecret.value)}}
    {{ randAlphaNum (.Values.ssoClient.secrets.ssoClientSecret.length | int) | b64enc }} 
    {{- else -}}
    {{ .Values.ssoClient.secrets.ssoClientSecret.value | b64enc }}
    {{- end }}

  # SSO_SESSION_SECRET - conditionally generate or use provided value
  ssoSessionSecret: |-
    {{- if and .Values.ssoClient.secrets.ssoSessionSecret.generate (not .Values.ssoClient.secrets.ssoSessionSecret.value)}}
    {{ randAlphaNum (.Values.ssoClient.secrets.ssoSessionSecret.length | int) | b64enc }} 
    {{- else}}
    {{ .Values.ssoClient.secrets.ssoSessionSecret.value | b64enc }}
    {{- end }}

  # SSO_REDIS_CONNECT_PASSWORD - conditionally generate or use provided value
  redisPassword: |-
    {{- if and .Values.redis.password.generate (not .Values.redis.password.value)}}
    {{ randAlphaNum (.Values.redis.password.length | int) | b64enc }}
    {{- else}}
    {{ .Values.redis.password.value | b64enc }}
    {{- end }}