# my-sso-app-chart/templates/sso-client-app/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sso-gateway.fullname" . }}-sso-client-secret
  labels:
    {{- include "sso-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: sso-client
type: Opaque
data:
  # Base64 encoded values. Replace with your actual base64 encoded values.
  # Use: echo -n 'YOUR_VALUE' | base64
  SSO_AUTH_SERVER_URL: {{ .Values.ssoClient.secrets.SSO_AUTH_SERVER_URL | quote }}
  SSO_REALM: {{ .Values.ssoClient.secrets.SSO_REALM | quote }}
  SSO_CLIENT_ID: {{ .Values.ssoClient.secrets.SSO_CLIENT_ID | quote }}
  SSO_CLIENT_SECRET: {{ .Values.ssoClient.secrets.SSO_CLIENT_SECRET | quote }}
  SSO_REDIRECT_URL: {{ .Values.ssoClient.secrets.SSO_REDIRECT_URL | quote }}
  SSO_LOGOUT_REDIRECT_URI: {{ .Values.ssoClient.secrets.SSO_LOGOUT_REDIRECT_URI | quote }}
  SSO_SESSION_SECRET: {{ .Values.ssoClient.secrets.SSO_SESSION_SECRET | quote }}
  CLIENT_HOST: {{ .Values.ssoClient.secrets.CLIENT_HOST | quote }}