apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssoGateway.fullname" . }}-client-svc
  labels:
    {{- include "ssoGateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ssoClient.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.ssoClient.service.port }}
      protocol: TCP
  selector:
    {{- include "ssoGateway.selectorLabels" . | nindent 4 }}
