{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssoGateway.fullname" . }}-redis
  labels:
    {{- include "ssoGateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "ssoGateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}