# sso-gateway/templates/nginx-proxy/configmap.yaml
{{- if .Values.nginx.enabled -}} # <-- Corrected: Changed .Values.nginx.enabled to .Values.nginx.enabled
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ssoGateway.fullname" . }}-nginx-config
  labels:
    {{- include "ssoGateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx-proxy
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        tcp_nopush      on;
        tcp_nodelay     on;
        keepalive_timeout  65;
        gzip  on;
        gzip_comp_level 5;
        gzip_min_length 256;
        gzip_proxied any;
        gzip_vary on;
        gzip_types
            application/javascript
            application/json
            application/x-javascript
            application/xml
            text/css
            text/javascript
            text/plain
            text/xml
            text/x-component;

        # Upstream SSO client application
        upstream sso_client_app {
            server {{ include "ssoGateway.fullname" . }}-client:{{ .Values.ssoClient.containerPort }};
        }

        # Dynamically generate server blocks for each configured server domain
        {{- $domains := list }}
        {{- if .Values.global.domains }}
          {{- $domains = (fromYaml .Values.keycloak.config) }}
        {{- end }}

        {{- range $domain := $domains }}
        server {
            listen {{ $.Values.nginx.containerPort }};
            server_name {{ $domain }};
            error_page 401 403 = @login_required;

            # headers for reverse proxy and SSO
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_connect_timeout       75s;
            proxy_send_timeout          75s;
            proxy_read_timeout          300s;

            location / {
                auth_request /auth/;
                auth_request_set $auth_status $upstream_status;
                proxy_pass http://sso_client_app;
            }

          location /auth/ {
            internal;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
            proxy_pass http://sso_client_app;
          }

          location /sso-login {
            proxy_set_header Host $host;
            proxy_pass http://sso_client_app/authn;
          }

          location /sso {
            proxy_set_header Host $host;
            proxy_pass http://sso_client_app/authn/callback;
          }

          location @login_required {
            return 302 {{ $domain }}/sso-login?relay=$request_uri;
          }
        }
        {{- end }}
    }
{{- end }}
