# my-sso-app-chart/templates/nginx-proxy/configmap.yaml
{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sso-gateway.fullname" . }}-nginx-proxy-config
  labels:
    {{- include "sso-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx-proxy
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        tcp_nopush      on;
        tcp_nodelay     on;
        keepalive_timeout  65;
        gzip  on;
        gzip_comp_level 5;
        gzip_min_length 256;
        gzip_proxied any;
        gzip_vary on;
        gzip_types
            application/javascript
            application/json
            application/x-javascript
            application/xml
            text/css
            text/javascript
            text/plain
            text/xml
            text/x-component;

        # Upstream to the SSO client application
        upstream sso_client_app {
            server {{ include "sso-gateway.fullname" . }}-sso-client:{{ .Values.ssoClient.containerPort }};
        }

        server {
            listen {{ .Values.nginx.containerPort }};
            server_name _; # Listen on all hostnames

            # Add appropriate headers for reverse proxy and SSO
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;

            # Adjust proxy timeouts if needed
            proxy_connect_timeout       60s;
            proxy_send_timeout          60s;
            proxy_read_timeout          60s;

            location / {
                proxy_pass http://sso-client-service:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-NginX-Proxy true;
                proxy_redirect off;

                proxy_buffers 8 16k;
                proxy_buffer_size 32k;
            }
        }
    }

