# my-sso-app-chart/templates/nginx-proxy/ingress.yaml
{{- if and .Values.nginx.enabled .Values.nginx.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sso-gateway.fullname" . }}-nginx-proxy
  labels:
    {{- include "sso-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx-proxy
  {{- with .Values.nginx.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.nginx.ingress.className }}
  ingressClassName: {{ .Values.nginx.ingress.className | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.nginx.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.nginx.ingress.path }}
            pathType: {{ .Values.nginx.ingress.pathType }}
            backend:
              service:
                name: {{ include "sso-gateway.fullname" . }}-nginx-proxy
                port:
                  number: {{ .Values.nginx.service.port }} # External port of NGINX Service
  {{- if .Values.nginx.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.nginx.ingress.host | quote }}
      secretName: {{ .Values.nginx.ingress.tls.secretName | quote }}
  {{- end }}
{{- end }}