# sso-gateway/templates/redis/pvc.yaml
{{- if and .Values.redis.enabled .Values.redis.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ssoGateway.fullname" . }}-redis-pvc
  labels:
    {{- include "ssoGateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
  {{- if .Values.redis.persistence.storageClassName }}
  storageClassName: {{ .Values.redis.persistence.storageClassName }}
  {{- end }}
{{- end }}