apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssoGateway.fullname" . }}
  labels:
    {{- include "ssoGateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ssoClient.autoscaling.enabled }}
  replicas: {{ .Values.ssoClient.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ssoGateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ssoClient.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ssoGateway.labels" . | nindent 8 }}
        {{- with .Values.ssoClient.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.ssoClient.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ssoGateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ssoClient.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.ssoClient.securityContext | nindent 12 }}
          image: {{ .Values.ssoClient.image.repository }}:{{ .Values.ssoClient.image.tag }}
          imagePullPolicy: {{ .Values.ssoClient.image.pullPolicy }} # <-- Corrected: Removed conditional 'if .Values.ssoClient.imagePullSecrets'
          ports: # <-- This block no longer conditional on 'nameOverride'
            - name: http
              containerPort: {{ .Values.ssoClient.service.containerPort }}
              protocol: TCP
          {{- if .Values.ssoClient.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.ssoClient.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.ssoClient.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.ssoClient.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.ssoClient.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.ssoClient.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.ssoClient.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.ssoClient.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.ssoClient.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.ssoClient.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.ssoClient.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.ssoClient.probes.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.ssoClient.resources | nindent 12 }}
          env:
            {{- toYaml .Values.ssoClient.env | nindent 12 }}
            {{- if .Values.ssoClient.envFromSecrets }}
            {{- range .Values.ssoClient.envFromSecrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .key }}
            {{- end }}
            {{- end }}
          envFrom:
            {{- if .Values.ssoClient.secretEnvSources }}
            {{- range .Values.ssoClient.secretEnvSources }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
            {{- end }}
          {{- with .Values.ssoClient.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.ssoClient.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ssoClient.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ssoClient.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ssoClient.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}