apiVersion: v1
kind: Service
metadata:
  name: {{ include "sso-gateway.fullname" . }}-client
  labels:
    {{- include "sso-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sso-gateway.selectorLabels" . | nindent 4 }}
